### ISSUE TITLE
Rename fxurl to something where a user doesn't change it

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/git-fleximod#31]
A user that edits .gitmodules to a hash/tag on their personal fork, will change fxtag and then naturally gravitates to fxurl.  I suggest that fxurl should be named something different.

**Comment by jedwards4b** [comment]
Any suggestions as to what it should be called?  fxbase?  fxdontmodifythisurl?

**Comment by cacraigucar** [comment]
I like fxdontmodifythisurl or maybe fxtestcommandurl.

Also, if you were to move this down after fxrequired in all the places in the .gitmodules file, users would be less likely to modify it as it would be separated from fxtag.

**Comment by wkchuang** [comment]
I tried changing tags/hashes and was confused by the url/fxurl as well, though the README was helpful in clarifying this. Changing the variable name to fxdontmodifythisurl would make it very clear. Another alternative may be changing "fxtag" to "tag", and the remaining "fx" to "fixed".

**Comment by jedwards4b** [comment]
@wkchuang thank you for the suggestions - we have renamed fxurl to be fxDONOTUSEurl 
I think that it is important to maintain the fx prefix since we are adding fields to a config file that
essentially belongs to git.  Using the fx prefix reduces the risk that git will use the same variable name for something else and clearly identifies the variable as part of the git-fleximod package.
